language: r
sudo: required
r_packages:
- knitr
r_github_packages:
- cloudyr/aws.signature
- jimhester/covr
- eddelbuettel/drat
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash drat.sh
